-- MySQL Script generated by MySQL Workbench
-- Sun Apr 16 04:40:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sysprog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sysprog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysprog` DEFAULT CHARACTER SET utf8 ;
USE `sysprog` ;

-- -----------------------------------------------------
-- Table `sysprog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysprog`.`user` ;

CREATE TABLE IF NOT EXISTS `sysprog`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `enabled` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysprog`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysprog`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `sysprog`.`user_roles` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_user_roles_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_roles_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `sysprog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
